name: Ricardo Harvin
favicon: null
layout_spectrum: 0.49604
typography_spectrum: 0.9445
title: Ricardo Harvin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebecda'
    - '#148291'
    - '#8cbab7'
    - '#172832'
    - '#44555c'
  brandStrength: 1
  lightness: 0.0625
  saturation: 0.7297277713660151
  rhythmicContrast: 0.24370172945782542
purpose: []
